In [1]:
import numpy as np

In [2]:
a=np.array([10,20,60])

In [3]:
type(a)

numpy.ndarray

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a[2]

60

In [8]:
a[-1]

60

In [9]:
a

array([10, 20, 60])

In [10]:
a[1:2]

array([20])

In [12]:
temp=[[1,2,3],[4,5,6]]

In [13]:
type(temp)

list

In [14]:
b1=np.array(temp)

In [15]:
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b1.ndim

2

In [17]:
b1.shape

(2, 3)

In [19]:
b1[:,1]

array([2, 5])

In [20]:
b1[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b1[-1,:]

array([4, 5, 6])

In [22]:
b2=b1

In [23]:
id(b1)

1799078590576

In [24]:
id(b2)

1799078590576

In [25]:
b2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b1[0,0]=500

In [28]:
b1

array([[500,   2,   3],
       [  4,   5,   6]])

In [29]:
b2

array([[500,   2,   3],
       [  4,   5,   6]])

In [30]:
b3=b1.copy

In [31]:
b3

<function ndarray.copy>

In [32]:
id(b1)

1799078590576

In [33]:
id(b3)

1799080214048

In [34]:
b3

<function ndarray.copy>

In [36]:
bbb=np.transpose(b1)

array([[500,   4],
       [  2,   5],
       [  3,   6]])

In [38]:
b1

array([[500,   2,   3],
       [  4,   5,   6]])

In [39]:
b1.shape

(2, 3)

In [41]:
temp=b1.reshape((1,6))

In [42]:
b1

array([[500,   2,   3],
       [  4,   5,   6]])

In [43]:
temp

array([[500,   2,   3,   4,   5,   6]])

In [44]:
temp.shape

(1, 6)

In [46]:
temp=b1.reshape(-1) ##flatten 

In [47]:
temp

array([500,   2,   3,   4,   5,   6])

In [48]:
temp.shape

(6,)

In [50]:
b2

array([[500,   2,   3],
       [  4,   5,   6]])

In [51]:
b1

array([[500,   2,   3],
       [  4,   5,   6]])

In [52]:
b_add=np.add(b1,b2)

In [53]:
b_add

array([[1000,    4,    6],
       [   8,   10,   12]])

In [58]:
b_temp=np.subtract(b_add,b1)

In [59]:
b_temp

array([[500,   2,   3],
       [  4,   5,   6]])

In [60]:
b_temp=np.divide(b_add,b1)

In [61]:
b_temp

array([[2., 2., 2.],
       [2., 2., 2.]])

In [63]:
b_mul=np.multiply(b1,b2)

In [64]:
b_mul

array([[250000,      4,      9],
       [    16,     25,     36]])

In [65]:
b_mull=np.dot(b1,b2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [66]:
b4=b2.reshape(3,2)

In [67]:
b4

array([[500,   2],
       [  3,   4],
       [  5,   6]])

In [68]:
b_mull=np.dot(b2,b4)

In [69]:
b_mull

array([[250021,   1026],
       [  2045,     64]])

In [70]:
b4

array([[500,   2],
       [  3,   4],
       [  5,   6]])

In [71]:
b2

array([[500,   2,   3],
       [  4,   5,   6]])

In [72]:
a

array([10, 20, 60])

In [73]:
np.max(a)

60

In [74]:
np.min(a)

10

In [75]:
np.mean(a)

30.0

In [76]:
np.std(a)

21.602468994692867

In [78]:
np.average(a)

30.0

In [80]:
np.sin(0)

0.0

In [81]:
np.sin(45)

0.8509035245341184

In [82]:
np.tan(45)

1.6197751905438615

In [83]:
np.sinh(90)

6.102016471589204e+38

In [89]:
np.sqrt(25)

5.0

In [84]:
np.log(100)

4.605170185988092

In [85]:
np.exp(0)

1.0

In [90]:
x=10 #1010

In [95]:
y=5 #1010

In [96]:
np.bitwise_or(x,y)

15

In [97]:
np.left_shift(x,2)

40

In [99]:
np.right_shift(y,1)

2

In [100]:
temp=np.zeros((5,5))

In [101]:
temp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [102]:
temp=np.ones((5,5))

In [103]:
temp

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])